# Generated by Django 2.1.3 on 2019-01-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20181219_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='beginning',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='ending',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='manifestation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='personal_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup',
            field=models.DateTimeField(null=True),
        ),
    ]
