# Generated by Django 2.1.3 on 2018-12-12 22:37

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/no-image.png', upload_to=products.models.upload_image_path),
        ),
    ]
