# Generated by Django 2.1.3 on 2019-02-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_quantity'),
        ('carts', '0003_auto_20190131_0644'),
        ('product_quantities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productquantity',
            unique_together={('cart', 'product')},
        ),
    ]
