# Generated by Django 2.1.3 on 2019-02-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_quantities', '0002_auto_20190203_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
