# Generated by Django 2.1.3 on 2019-01-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190114_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
