# Generated by Django 2.1.3 on 2019-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='expires',
            field=models.IntegerField(default=999),
        ),
    ]
