# Generated by Django 2.1.3 on 2019-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190120_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='expires',
            field=models.IntegerField(default=7),
        ),
    ]
