# Generated by Django 2.1.3 on 2019-01-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190121_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernameactivation',
            name='email',
        ),
    ]
